[tool.black]
line-length = 120
py36 = true
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.ropeproject
  | \.tox
  | venv.*
  | _build
  | buck-out
  | build
  | dist
  | profiling
)/
'''

[tool.mypy]
ignore_missing_imports = true

[tool.ruff]
line-length = 120
target-version = "py310"
select = ["ALL"]
ignore = [
    "D203",  # Conflicts with D211 and spams useless warnings about ruff auto-disabling it
    "D213",  # Conflicts with D212 and spams useless warnings about ruff auto-disabling it
]

#[tool.ruff.per-file-ignores]
#"tests/*" = ["S101", "SLF001"]
