[tool.black]
line-length = 88
py36 = true
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.ropeproject
  | \.tox
  | venv.*
  | _build
  | buck-out
  | build
  | dist
  | profiling
)/
'''
